decwar,blkdat,basbld,baskil,baspha,build,captur,check,chkpnt,clrbuf
damage,dist,dock,dship,endgam,energy,free,getcmd,jump,kqsrch,list
locate,lstscn,lstflg,lstupd,lstout,lstsum,lstobj,move,nova,outhit,outmsg
paswrd,phacon,place,plnatk,plnrmv,points,pridis,prloc,prompt,radio,repair
romdrv,romstr,romtor,scan,set,shield,snova,status,tell,time,tordam,torp,tractr
trap,type,users,low,high,msg,warmac,warver,setup,setmsg
