C	This file is part of Decwar.
C	Copyright 1979, 2011 Bob Hysick, Jeff Potter, The University of Texas
C	Computation Center and Harris Newman.

C	This program is free software; you can redistribute it and/or modify
C	it under the terms of the GNU General Public License as published by
C	the Free Software Foundation; either version 3, or (at your option)
C	any later version.

C	This program is distributed in the hope that it will be useful,
C	but WITHOUT ANY WARRANTY; without even the implied warranty of
C	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
C	GNU General Public License for more details.

C	You should have received a copy of the GNU General Public License
C	along with this program; if not, write to the Free Software
C	Foundation, Inc., 51 Franklin Street - Fifth Floor, Boston, MA
C	02110-1301, USA.  


	external backup !) 10,10,10,10,10,10,10,10,0,!
	external kilch4 !You are scheduled for reincarnation in !
	external kilch5 ! minutes and !
	external kilch6 ! seconds.!
	external kilch8 !!
			!Time left:  !
	external maicom !This command unavailable in Pre-game !
	external nogal1 !This particular galaxy has been depopulated!!!
			!Please try again.  A new battle is forming now!!!
	external pgame1 !!
			!Now entering DECWAR Pre-game, type Activate to enter/reenter game.!
	external ptywrn !DECWAR may not be played from a PTY.!
	external setu01 !Sorry, but all ships are in use.  Try again later.!
	external setu02 !Regular or Tournament game? (Regular) !
	external setu03 !Tournament name or number: !
	external setu04 !!
			!Is the Romulan Empire involved in this conflict? (yes) !
	external setu05 !!
			!Do you want black holes? (no) !
	external setu11 !!
			!You will join the forces of the Federation.!
	external setu12 !!
			!You will join the forces of the Klingon Empire.!
	external setu13 !!
			!The following vessels are available for you to use.!
	external setu14 !!
			!Which vessel do you wish to command? !
	external setu15 !!
			!Sorry, that vessel is being used.!
	external setu16 !!
			!Currently there are !
	external setu17 ! Federation ships and !
	external stu17a ! Empire ships. !
	external setu18	!Which side do you wish to join? (Federation or Empire) !
	external strtup !!
			!Type HELP for help, PREGAME to enter Pre-game, or <CR>.  !



