#!/bin/bash

#source=../algebra/algebra.for
source=../inverse/inverse.for

cat $source > job.for
sed -i -e 's/nout = 6/nout = 5/g' job.for
./back10 -cf ./job.tap job.for
./back10 -lf ./job.tap

./dec10 simh/for-runner.ini

