	external backup !) 10,10,10,10,10,10,10,10,0,!
	external kilch4 !You are scheduled for reincarnation in !
	external kilch5 ! minutes and !
	external kilch6 ! seconds.!
	external kilch8 !!
			!Time left:  !
	external maicom !This command unavailable in Pre-game !
	external nogal1 !This particular galaxy has been depopulated!!!
			!Please try again.  A new battle is forming now!!!
	external pgame1 !!
			!Now entering DECWAR Pre-game, type Activate to enter/reenter game.!
	external ptywrn !DECWAR may not be played from a PTY.!
	external setu01 !Sorry, but all ships are in use.  Try again later.!
	external setu02 !Regular or Tournament game? (Regular) !
	external setu03 !Tournament name or number: !
	external setu04 !!
			!Is the Romulan Empire involved in this conflict? (yes) !
	external setu05 !!
			!Do you want black holes? (no) !
	external setu11 !!
			!You will join the forces of the Federation.!
	external setu12 !!
			!You will join the forces of the Klingon Empire.!
	external setu13 !!
			!The following vessels are available for you to use.!
	external setu14 !!
			!Which vessel do you wish to command? !
	external setu15 !!
			!Sorry, that vessel is being used.!
	external setu16 !!
			!Currently there are !
	external setu17 ! Federation ships and !
	external stu17a ! Empire ships. !
	external setu18	!Which side do you wish to join? (Federation or Empire) !
	external strtup !!
			!Type HELP for help, PREGAME to enter Pre-game, or <CR>.  !
